version: "3"

services:
  app:
    build: .
    container_name: laravel-app
    working_dir: /var/www/html
    # volumes:
    #  - .:/var/www/html
    #  - /var/www/html/vendor
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
    command: php artisan serve --host=0.0.0.0 --port=8000
